[manifest]
version = "1.0.0"
priority = 2147483647

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Credit Card' then
            G.GAME.bankrupt_at = G.GAME.bankrupt_at - self.ability.extra
        end'''
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Cloud 9' and self.ability.nine_tally and self.ability.nine_tally > 0 then'''
position = "at"
payload = '''if false then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Credit Card' then
            G.GAME.bankrupt_at = G.GAME.bankrupt_at + self.ability.extra
        end'''
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Business Card' and'''
position = "after"
payload = '''false and -- Removed by Madness'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Stuntman' then
            G.hand:change_size(-self.ability.extra.h_size)
        end'''
position = "after"
payload = ''']]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Stuntman' then
            G.hand:change_size(self.ability.extra.h_size)
        end'''
position = "after"
payload = ''']]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Spare Trousers' and (next(context.poker_hands['Two Pair']) or next(context.poker_hands['Full House'])) and not context.blueprint then'''
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Caino' and self.ability.caino_xmult > 1 then 
                            return {
                                message = localize{type='variable',key='a_xmult',vars={self.ability.caino_xmult}},
                                Xmult_mod = self.ability.caino_xmult
                            }
                        end'''
position = "after"
payload = ''']]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Caino' and to_big(self.ability.caino_xmult) > to_big(1) then
                            return {
                                message = localize{type='variable',key='a_xmult',vars={self.ability.caino_xmult}},
                                Xmult_mod = self.ability.caino_xmult
                            }
                        end'''
position = "after"
payload = ''']]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Misprint' then
            local r_mults = {}'''
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''colours = {G.C.UI.TEXT_DARK},pop_in_rate = 9999999, silent = true, random_element = true, pop_delay = 0.2011, scale = 0.32, min_cycle_time = 0})}},
            }'''
position = "after"
payload = '''--]]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Gros Michel' then loc_vars = {self.ability.extra.mult, SMODS.get_probability_vars(self, 1, self.ability.extra.odds, 'gros_michel')}'''
position = "at"
payload = '''elseif self.ability.name == 'Gros Michel' then -- Removed by Madness'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Erosion' then loc_vars = {self.ability.extra, math.max(0,self.ability.extra*(G.playing_cards and (G.GAME.starting_deck_size - #G.playing_cards) or 0)), G.GAME.starting_deck_size}'''
position = "at"
payload = '''elseif self.ability.name == 'Erosion' then -- Removed by Madness'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Castle' then loc_vars = {self.ability.extra.chip_mod, localize(G.GAME.current_round.castle_card.suit, 'suits_singular'), self.ability.extra.chips, colours = {G.C.SUITS[G.GAME.current_round.castle_card.suit]}}'''
position = "at"
payload = '''elseif self.ability.name == 'Castle' then -- Removed by Madness'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Walkie Talkie' then loc_vars = {self.ability.extra.chips, self.ability.extra.mult}'''
position = "at"
payload = '''elseif self.ability.name == 'Walkie Talkie' then -- Removed by Madness'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Certificate' then'''
position = "at"
payload = '''if self.ability.name == 'Certificate' and false then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Bloodstone' then '''
position = "at"
payload = '''elseif self.ability.name == 'Bloodstone' and false then -- Removed by Madness'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''colours = {G.C.UI.TEXT_DARK},pop_in_rate = 9999999, silent = true, random_element = true, pop_delay = 0.2011, scale = 0.32, min_cycle_time = 0})}},
            }'''
position = "after"
payload = '''--]]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif context.setting_blind and not self.getting_sliced then'''
position = "after"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif context.destroying_card and not context.blueprint then'''
position = "before"
payload = '''--]]'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Campfire' and not context.blueprint and self ~= context.card then'''
position = "at"
payload = '''if false then -- Removed by Madness'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Raised Fist' then'''
position = "at"
payload = '''elseif self.ability.name == 'Raised Fist' then loc_vars = {self.ability.extra.mult}'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Gros Michel' or self.ability.name == 'Cavendish' then'''
position = "at"
payload = '''if false then'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Ride the Bus' and not context.blueprint then'''
position = "at"
payload = '''if false then'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Hit the Road' and self.ability.x_mult > 1 then'''
position = "at"
payload = '''if false then'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif self.ability.name == 'Invisible Joker' then loc_vars = {self.ability.extra, self.ability.invis_rounds}'''
position = "at"
payload = '''elseif self.ability.name == 'Invisible Joker' then -- Removed by Madness'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _c.name == 'Invisible Joker' then'''
position = "at"
payload = '''elseif false then -- Removed by Madness'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif context.cards_destroyed then'''
position = "at"
payload = '''elseif false then -- Removed by Madness'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Satellite' then'''
position = "at"
payload = '''if self.ability.name == 'Satellite' and false then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif context.discard then'''
position = "after"
payload = '''--[['''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''elseif context.end_of_round then'''
position = "before"
payload = ''']]'''
times = 1
match_indent = true