[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not skip_increment then G.GAME.current_round.reroll_cost_increase = G.GAME.current_round.reroll_cost_increase + 1 end"
position = "before"
payload = '''
if next(SMODS.find_card("j_chaos", false)) then 
    skip_increment = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '=[SMODS Cryptid "lib/overrides.lua"]'
pattern = "function calculate_reroll_cost(skip_increment)"
position = "after"
payload = '''
if next(SMODS.find_card("j_chaos", false)) then 
    skip_increment = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "inc_career_stat('c_shop_rerolls', 1)"
position = "after"
payload = "G.GAME.reroll_tally = (G.GAME.reroll_tally or 0) + 1"
match_indent = true
times = 1