[manifest]
version = "1.0.0"
priority = -2147483648

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local game_over = true"
position = "before"
payload = '''
local return_to_shop = false
'''
match_indent = false
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then"
position = "before"
payload = '''

for i = 1, #G.jokers.cards do
    local eval = nil
    eval = G.jokers.cards[i]:calculate_joker({check_return_to_shop = true, game_over = game_over})
    if eval then
        game_over = false
        return_to_shop = return_to_shop or eval.return_to_shop
        card_eval_status_text(G.jokers.cards[i], 'jokers', nil, nil, nil, eval)
    end
end
if return_to_shop then
    MADNESS.return_to_shop(return_to_shop)
    return true
end
'''
match_indent = true
times = 1
